### ISSUE TITLE
Code Integration mit minted-package unter Windows

### ISSUE THREAD

**Issue by simonbiwer** [blackapple113/H-BRS-Thesisvorlage#28]
Zur Code-Integration wird das package minted verwendet, welches einen Python-Interpreter benötigt. Da dieser (unter Windows) nicht mit dem Befehl "python" oder "python3" startbar ist, muss der Befehl zu "py" geändert werden. Dies kann durch das Einfügen der Zeile

\renewcommand{\MintedPython}{py}

gelöst werden.

**Comment by blackapple113** [comment]
Kann eventuell mit dem Paket `ifplatform` [siehe hier](https://ctan.org/pkg/ifplatform) automatisiert gelöst werden.

**Comment by blackapple113** [comment]
Das Problem scheint sich geklärt zu haben. Tatsächlich scheint ein Neustart von VSCode nach der Installation von Pygments notwendig zu sein, da sonst die Shell im Hintergrund nicht neu geladen wird.
